# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XSs6GUsnnj7_dt9yLE4zoch5cJOvmUFW
"""

import streamlit as st
import google.generativeai as genai
import folium
from streamlit_folium import st_folium
import re

# 1. 보안 설정: Streamlit 클라우드의 Secrets 기능을 사용합니다.
if "GEMINI_API_KEY" in st.secrets:
    genai.configure(api_key=st.secrets["GEMINI_API_KEY"])
else:
    st.error("설정에서 GEMINI_API_KEY를 입력해주세요.")

st.set_page_config(page_title="Mood Food AI", layout="wide", page_icon="🍱")

# PWA 연결 및 모바일 최적화 메타데이터
st.markdown("""
    <link rel="manifest" href="./manifest.json">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="apple-mobile-web-app-status-bar-style" content="black">
    <style>
        .stButton>button { border-radius: 12px; height: 3em; font-size: 18px !important; }
    </style>
""", unsafe_allow_html=True)

st.title("🌍 10가지 기분별 메뉴 추천 🍱")

# 클라우드 환경에서 가장 안정적인 최신 모델 명칭[cite: 2]
VALID_MODEL = "models/gemini-flash-latest"

mood_map = {
    "🔥": "스트레스", "😔": "우울", "🧠": "집중 필요", "🥳": "판타스틱",
    "😴": "졸림", "😤": "화남", "🥗": "다이어트 중", "😭": "속상함",
    "😷": "감기 기운", "🥵": "열이 남"
}

col1, col2 = st.columns([1, 1.2])

with col1:
    st.subheader("지금 기분은 어떠신가요?")
    items = list(mood_map.items())
    user_input = None
    for i in range(2):
        btn_cols = st.columns(5)
        for j in range(5):
            idx = i * 5 + j
            if idx < len(items):
                emoji, meaning = items[idx]
                if btn_cols[j].button(emoji, key=f"mood_{idx}", use_container_width=True):
                    user_input = meaning

# 성균관대 좌표 설정[cite: 2]
SKKU_LAT, SKKU_LON = 37.2937156, 126.974337
with col2:
    st.write("### 📍 내 주변 식당 지점 (성균관대)")
    m = folium.Map(location=[SKKU_LAT, SKKU_LON], zoom_start=15)
    folium.Marker([SKKU_LAT, SKKU_LON], popup="내 위치", icon=folium.Icon(color='red')).add_to(m)
    st_folium(m, width=600, height=450, key="main_map")

if user_input:
    with st.spinner(f"AI가 {user_input}에 어울리는 메뉴를 고르고 있습니다..."):
        try:
            # Gemini 3 Flash 모델 호출[cite: 2]
            model = genai.GenerativeModel(VALID_MODEL)
            prompt = f"기분이 {user_input}일 때 먹기 좋은 전 세계 요리 1가지를 [음식명] 형식으로 다정하게 추천해줘."
            response = model.generate_content(prompt)
            res_text = response.text
            match = re.search(r"\[(.*?)\]", res_text)
            food_keyword = match.group(1) if match else user_input

            with col1:
                st.write("---")
                st.success(f"### 🍱 추천: {food_keyword}")
                st.write(res_text)
                st.markdown(f"[👉 네이버 지도에서 검색](https://map.naver.com/v5/search/{food_keyword}%20맛집)")
        except Exception as e:
            st.error(f"연결 실패: {e}")

st.divider()
st.caption(f"Engine: {VALID_MODEL} | Powered by Gemini 3 Flash")